#!/bin/sh


cat ../../js/settings.js ../../js/vendors/*.js ../../js/app/*.js ../../js/main.js > ../../dist/js/scripts.js
node_modules/uglify-js/bin/uglifyjs --compress warnings=true --mangle --output ../../dist/js/scripts.tmp.js ../../dist/js/scripts.js
echo -en "/**\n * DO NOT EDIT THIS FILE DIRECTLY!\n * \n * This script is compiled from source.\n *\n * @author Matthew Dunham <matt@hotcoffeydesign.com>\n **/\n\n" | cat - ../../dist/js/scripts.tmp.js > ../../dist/js/scripts.min.js
rm ../../dist/js/scripts.tmp.js